# Generated by Django 4.2.1 on 2023-05-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='post',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
